class Config:
    """配置常量类，包含下载、解析等功能的配置参数"""
    
    DEFAULT_TIMEOUT = 30
    VIDEO_SIZE_CHECK_TIMEOUT = 10
    IMAGE_DOWNLOAD_TIMEOUT = 10
    VIDEO_DOWNLOAD_TIMEOUT = 300
    
    DEFAULT_LARGE_VIDEO_THRESHOLD_MB = 40.0
    MAX_LARGE_VIDEO_THRESHOLD_MB = 100.0
    
    STREAM_DOWNLOAD_CHUNK_SIZE = 2 * 1024 * 1024
    
    RANGE_DOWNLOAD_CHUNK_SIZE = 2 * 1024 * 1024
    RANGE_DOWNLOAD_MAX_CONCURRENT = 64
    
    M3U8_MAX_CONCURRENT_SEGMENTS = 10
    
    DOWNLOAD_MANAGER_MAX_CONCURRENT = 5
    PARSER_MAX_CONCURRENT = 10
    
    DEFAULT_CACHE_DIR = "/app/sharedFolder/video_parser/cache"

